{% set version = "1.35.0" %}

package:
  name: grpcio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/grpcio/grpcio-{{ version }}.tar.gz
  sha256: 7bd0ebbb14dde78bf66a1162efd29d3393e4e943952e2f339757aa48a184645c
  patches:
    - 0001-Monkey-patch-distutils.ccompiler.spawn-to-elide-std-.patch
    - 0002-windows-ssl-lib-names.patch
    - 0001-fix-win-setup-cmds.patch

build:
  number: 0
  # protobuf does not support Visual C++ 2008, skip windows py27
  skip: True  # [win and vc<10]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - six >=1.5.2
    - futures >=2.2.0   # [py27]
    - enum34 >=1.0.4    # [py27]
    - zlib
    - openssl
    - c-ares            # [unix]
  run:
    - python
    - setuptools
    - six >=1.5.2
    - futures >=2.2.0   # [py27]
    - enum34 >=1.0.4    # [py27]
    - zlib
    - openssl
    - {{ pin_compatible("c-ares") }}  # [unix]

test:
  imports:
    - grpc
    - grpc._cython
    - grpc._cython._cygrpc
    - grpc.beta
    - grpc.framework
    - grpc.framework.common
    - grpc.framework.foundation
    - grpc.framework.interfaces
    - grpc.framework.interfaces.base
    - grpc.framework.interfaces.face

about:
  home: https://grpc.io
  license: Apache 2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  license_family: APACHE
  summary: HTTP/2-based RPC framework

extra:
  recipe-maintainers:
    - ocefpaf
