travis:
  secure:
    BINSTAR_TOKEN: MhzgsrRa8lA642Sdw29ZhiSkSNJAsG6/Yq55ssNlIUii3rIUG1guKF9EWwpkEjND5K20QTpk542ewgIfYcgwNBnU3v2GSlD5JRM5cfdqshnG+0yiMT5r7OSSnnmscz5RzjkLZRYzxNcG9l2VROHDlPJhHOQFJCXMWp4TBRwWNPKEl78YXV5g6hC1cK5adPvE+z0AE3CuLx2WKB50D+rPKNFCaK1hMvEQwshGzR7rrfctN7/MiXdVtnsNNerR1cdxd1mTiVEKKiPph0yBfl52PhuCa4FyMQ+8ku5fPEJri0kr2jINXTc/FYJunXyVySayycPMkIc0Mm9RGdF8bJm7ND/qGpz7UKAqcz43q/d9uvNq02CU4nxpreeEfrUSiiFWNwovoaETYLtpbW34AExI5/OXc8m7QlQLh9mgMDG4CQE02x2AMdhjS0sBMhww3JQBQUTAywruNsawx1h1b12dwowZ+syRxuvLKJPUkCvQ8CX7+aLofki5vAul8z1iPXwL2dlm9BweGeiZEYVUvxIEK3KHbUe0VRw2iET3o0gYcEWlFxEql9wgUf/xWqRzpNOuaOf4BWPblFnUn5/mTAjnBYZYLxanGSJ4tP2s/CfLF2KgucMDQvPr7wXPbOLWYzy4iK4oh1FVQ+7lo8qOS35R5K3/Pft+PC/O0RXYvX0geTg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
